All: senhack genhack

senhack:
	g++ -I./ -o sample_set_enhack sample_set_enhack.cpp -L/usr/lib -llazurite

genhack:
	g++ -I./ -o sample_get_enhack sample_get_enhack.cpp -L/usr/lib -llazurite

clean:
	rm sample_set_enhack sample_get_enhack
